server:
  port: 8080
  allowed_redirects:
    - "<YOUR_FRONTEND_URL>" # Add your frontend URL here
    - "<ANOTHER_FRONTEND_URL>" # Add another frontend URL here

db: # postgresql database configuration
  host: <YOUR_DB_HOST>
  port: <YOUR_DB_PORT>
  user: <YOUR_DB_USER>
  password: <YOUR_DB_PASSWORD>
  database: <YOUR_DB_NAME>

auth:
  jwt:
    private_key: "configs/server.key" # Path to your private key -> generate with `make generate-cert`
    public_key: "configs/server.pem" # Path to your public key -> generate with `make generate-cert`
    access_token_expiration: 300 # Access token expiration time in seconds
    refresh_token_expiration: 604800 # Refresh token expiration time in seconds
  google:
    client_id: "<YOUR_GOOGLE_CLIENT_ID>" # Set your Google client ID here
    client_secret: "<YOUR_GOOGLE_CLIENT_SECRET>" # Set your Google client secret here
    redirect_url: "<YOUR_BACKEND_CALLBACK_URL>" # Your Backend Callback URL
  discord:
    client_id: "<YOUR_DISCORD_CLIENT_ID>"
    client_secret: "<YOUR_DISCORD_CLIENT_SECRET>"
    redirect_url: "<YOUR_DISCORD_REDIRECT_URL>"
  encryption_key: "<ENCRYPTION_KEY>" # Your encryption key
